---
title: "euk_asvs_mgns_regressions"
output: html_document
date: "2024-06-13"
---

### Library Loading
```{r}
library(here)
library(tidyverse)
library(RColorBrewer)
library(ggplot2)
library(purrr)
library(Polychrome)
library(ggallin)
library(ggrepel)
```

### Load  data
```{r}
taxa_18S <- read.csv(file=here("18S Comparison","Phylum_Class_18S_samplepairs.csv"))
taxa_COI <- read.csv(file=here("COI Comparison","Phylum_Class_COI_samplepairs.csv"))
```

Group data by Phylum, sum up read and metagenome counts for each Class

# 18S
```{r}
# sum relative abundances across all samples 
keeps <- c('Phylum', 'percent_TPM', 'X18S.reads')
taxa_phy <- taxa_18S[keeps] 

taxa_phy_sum <- taxa_phy %>% group_by(Phylum) %>%
  summarise(mgn_sum=sum(percent_TPM),
            reads_sum=sum(X18S.reads),
            .groups = 'drop')

# subset only for taxa with a combined relative abundance >1% in either data set
taxa_phy_sum_filt <- taxa_phy_sum[taxa_phy_sum$mgn_sum > 0.02 |
                            taxa_phy_sum$reads_sum > 0.02, ]

phyla_to_keep <- taxa_phy_sum_filt$Phylum

taxa_phy_filt_18S <- taxa_18S[taxa_18S$Phylum %in% phyla_to_keep, ] %>%
  group_by(Metagenome.sample, ASV.sample, Phylum) %>%
  summarise(mgn_sum=sum(percent_TPM),
            reads_sum=sum(X18S.reads),
            .groups = 'drop')
```

# COI
```{r}
# sum relative abundances across all samples 
keeps <- c('Phylum', 'percent_TPM', 'COI.reads')
taxa_phy <- taxa_COI[keeps] 

taxa_phy_sum <- taxa_phy %>% group_by(Phylum) %>%
  summarise(mgn_sum=sum(percent_TPM),
            reads_sum=sum(COI.reads),
            .groups = 'drop')

# subset only for taxa with a combined relative abundance >1% in either data set
taxa_phy_sum_filt <- taxa_phy_sum[taxa_phy_sum$mgn_sum > 0.01 |
                            taxa_phy_sum$reads_sum > 0.01, ]

phyla_to_keep <- taxa_phy_sum_filt$Phylum

taxa_phy_filt_COI <- taxa_COI[taxa_COI$Phylum %in% phyla_to_keep, ] %>%
  group_by(Metagenome.sample, ASV.sample, Phylum) %>%
  summarise(mgn_sum=sum(percent_TPM),
            reads_sum=sum(COI.reads),
            .groups = 'drop')
```

### Scatter plot of all Phyla
```{r}
# create color palette
P50 = createPalette(55, c("#ff0000", "#00ff00", "#0000ff"))
P50 <- sortByHue(P50)
P50 <- as.vector(t(matrix(P50)))
names(P50) <- NULL

taxa_phy_plot$Phylum <- factor(taxa_phy_plot$Phylum, 
                               levels=phy_unique_ordered)
  
p <- ggplot(taxa_phy_plot, aes(x=reads_sum, y=mgn_sum, color=Phylum)) +
  geom_point(show.legend=TRUE) +
  labs(title = paste("Eukaryotic phyla in paired metagenome & 18S samples"),
         x="Fraction of COI reads", y="Fraction of eukaryotic metagenome contigs") +
  coord_cartesian(xlim = c(0, max(taxa_phy$reads_sum) + (0.1*max(taxa_phy$reads_sum))),
                    ylim = c(0, max(taxa_phy$mgn_sum) + 0.1*max(taxa_phy$mgn_sum))) +
  scale_x_continuous(expand=c(0, 0)) + scale_y_continuous(expand=c(0, 0)) +
  labs(color="Phylum") +
  theme_classic() +
  scale_color_manual(values=P50)

ggsave(here("COI Comparison", "Euk_phyla_COI_comparison.png"),
       p,width=12, height=6, dpi=300, units="in")
```

### Assess each Phylum

## COI
```{r split}
# Split the data into subsets based on Phylum
data_splits_COI <- split(taxa_phy_filt_COI, taxa_phy_filt_COI$Phylum)
```

## 18S
```{r split}
# Split the data into subsets based on Phylum
data_splits_18S <- split(taxa_phy_filt_18S, taxa_phy_filt_18S$Phylum)
```

# COI
```{r COI}
# Initialize a list to store the linear regression models and correlation coefficients

## COI
lm_models_COI <- list()
r_squareds_COI <- vector("numeric", length(data_splits_COI))
reads_max_COI <- vector("numeric", length(data_splits_COI))
slopes_COI <- vector("numeric", length(data_splits_COI))
pearsons_COI <- vector("numeric", length(data_splits_COI))
```

## 18S
```{r 18S}
# Initialize a list to store the linear regression models and R-squared values

lm_models_18S <- list()
r_squareds_18S <- vector("numeric", length(data_splits_18S))
pearsons_18S <- vector("numeric", length(data_splits_18S))
reads_max_18S <- vector("numeric", length(data_splits_18S))
slopes_18S <- vector("numeric", length(data_splits_18S))
```

# COI
```{r}
# Loop through the subsets and fit linear regression models
# Save r-squared values, max read counts, and model coefficients in separate vectors

# Initialize data frame of Pearson's values for later plotting
  pearsons_viol_COI <- data.frame(Phylum = character(), 
                              Pearsons = numeric(), 
                              stringsAsFactors = FALSE)

for (i in seq_along(data_splits_COI)) {
  subset_data <- data_splits_COI[[i]]
  lm_models_COI[[i]] <- lm(reads_sum ~ mgn_sum, data = subset_data)
  r_squareds_COI[i] <- summary(lm_models_COI[[i]])$r.squared
  reads_max_COI[i] <- max(subset_data$reads_sum)
  slopes_COI[i] <- coef(lm_models_COI[[i]])[2]
  pearsons_COI[i] <- sqrt(r_squareds_COI[i]) * sign(slopes_COI[i])
  
  # Fill in the Pearsons data frame
  pearsons_viol_COI <- rbind(pearsons_viol_COI, data.frame(Phylum = subset_data$Phylum[1], 
                                       Pearsons = pearsons_COI[i], 
                                       stringsAsFactors = FALSE))
  
  # Create a scatter plot for the subset
  scatter_plot <- ggplot(subset_data, aes(x=reads_sum, y=mgn_sum)) +
    geom_point(color="#0072B2") +
    geom_smooth(method="lm", se=TRUE, color="black", linewidth=0.5) +
    labs(title = paste("Phylum: ", subset_data$Phylum[1]),
         x="Fraction of COI reads", y="Fraction of eukaryotic metagenome contigs") +
    annotate(geom="text", label = paste("Pearson's r = ", round(pearsons_COI[i], 2)),
             x=max(subset_data$reads_sum) - (0.2*max(subset_data$reads_sum)), 
              y=max(subset_data$mgn_sum) - 0.5*max(subset_data$mgn_sum),
              color="black", hjust=0, vjust=1) +
    annotate(geom="text", label = paste("Slope = ", round(slopes_COI[i], 2)),
             x=max(subset_data$reads_sum) - (0.2*max(subset_data$reads_sum)), 
              y=max(subset_data$mgn_sum) - 0.55*max(subset_data$mgn_sum),
              color="black", hjust=0, vjust=1) +
    coord_cartesian(xlim = c(0, max(subset_data$reads_sum) +
                               (0.1*max(subset_data$reads_sum))), 
                    ylim = c(0, max(subset_data$mgn_sum) + 0.1*max(subset_data$mgn_sum))) +
    scale_x_continuous(expand=c(0, 0)) + scale_y_continuous(expand=c(0, 0)) +
    theme_classic()
  
  # Generate a unique filename
  
  name <- as.character(subset_data$Phylum)[1]  # Make sure it's a single string
  file_path <- here("COI Comparison", "Phylum plots", paste0("COI_", name, ".png"))
  
  # Save the plot
  ggsave(filename = file_path, scatter_plot, width = 7, 
         height = 5, dpi = 300, units = "in")
}
```

# 18S
```{r}
# Initialize data frame of Pearson's values for later plotting
pearsons_viol_18S <- data.frame(Phylum = character(), 
                              Pearsons = numeric(), 
                              stringsAsFactors = FALSE)

# Loop through the subsets and fit linear regression models
# Save r-squared values, max read counts, and model coefficients in separate vectors
for (i in seq_along(data_splits_18S)) {
  subset_data <- data_splits_18S[[i]]
  lm_models_18S[[i]] <- lm(reads_sum ~ mgn_sum, data = subset_data)
  r_squareds_18S[i] <- summary(lm_models_18S[[i]])$r.squared
  reads_max_18S[i] <- max(subset_data$reads_sum)
  slopes_18S[i] <- coef(lm_models_18S[[i]])[2]
  pearsons_18S[i] <- sqrt(r_squareds_18S[i]) * sign(slopes_18S[i])
  
  # Fill in the Pearsons data frame
  pearsons_viol_18S <- rbind(pearsons_viol_18S, data.frame(Phylum = subset_data$Phylum[1], 
                                       Pearsons = pearsons_18S[i], 
                                       stringsAsFactors = FALSE))

# Create a scatter plot for the subset
  scatter_plot <- ggplot(subset_data, aes(x=reads_sum, y=mgn_sum)) +
    geom_point(color="#0072B2") +
    geom_smooth(method="lm", se=TRUE, color="black", linewidth=0.5) +
    labs(title = paste("Phylum: ", subset_data$Phylum[1]),
         x="Fraction of 18S reads", y="Fraction of eukaryotic metagenome contigs") +
    annotate(geom="text", label = paste("Pearson's r = ", round(pearsons_18S[i], 2)),
             x=max(subset_data$reads_sum) - (0.2*max(subset_data$reads_sum)), 
              y=max(subset_data$mgn_sum) - 0.5*max(subset_data$mgn_sum),
              color="black", hjust=0, vjust=1) +
    annotate(geom="text", label = paste("Slope = ", round(slopes_18S[i], 2)),
             x=max(subset_data$reads_sum) - (0.2*max(subset_data$reads_sum)), 
              y=max(subset_data$mgn_sum) - 0.55*max(subset_data$mgn_sum),
              color="black", hjust=0, vjust=1) +
    coord_cartesian(xlim = c(0, max(subset_data$reads_sum) +
                               (0.1*max(subset_data$reads_sum))), 
                    ylim = c(0, max(subset_data$mgn_sum) + 0.1*max(subset_data$mgn_sum))) +
    scale_x_continuous(expand=c(0, 0)) + scale_y_continuous(expand=c(0, 0)) +
    theme_classic()

  # Generate a unique filename

  name <- as.character(subset_data$Phylum)[1]  # Make sure it's a single string
  file_path <- here("18S Comparison", "Phylum plots", paste0("18S_", name, ".png"))
  
  # Save the plot
  ggsave(filename = file_path, scatter_plot, width = 7, 
         height = 5, dpi = 300, units = "in")
  }
```

### Plot violin of Pearson's correlation coefficients
```{r}
# create color palette
P20 = createPalette(10, c("#ff0000", "#00ff00", "#0000ff"))
P20 <- sortByHue(P20)
P20 <- as.vector(t(matrix(P20)))
names(P20) <- NULL

# Replace Pearson coefficient NAs with 0s
pearsons_viol_COI[is.na(pearsons_viol_COI)] <- 0
pearsons_viol_18S[is.na(pearsons_viol_18S)] <- 0

pearsons_viol_COI$Marker_gene <- 'COI'
pearsons_viol_18S$Marker_gene <- '18S'

# Combined df of both markers
pearsons_viol <- bind_rows(pearsons_viol_COI, pearsons_viol_18S)
pearsons_viol$Pearsons <- as.numeric(pearsons_viol$Pearsons)

# Add conditional color group
pearsons_viol <- pearsons_viol %>%
  mutate(color_group = ifelse(Pearsons > 0.4, as.character(Phylum), NA))

# Plot
p <- ggplot(pearsons_viol, aes(Marker_gene, Pearsons)) +
  geom_violin() + 
  geom_jitter(aes(color = color_group), 
              size = 2,
              width = 0.1) +
  scale_color_manual(values = P20,
                     na.value = "grey") +
  stat_summary(fun.data = "mean_cl_boot", 
               geom = "pointrange",
               color = "black") +
  theme_classic() +
  labs(x = "Marker gene",
       y = expression("Metagenome:marker gene relative abundance correlation (Pearson's " * italic("r") * ")"),
       color = expression("Phylum (Pearson's " * italic("r") *
       " > 0.4)"))

write.csv(pearsons_viol, here("Mgn_ASV_phylum_pearsonsr.csv"), row.names=FALSE)

#ggsave(here("Diversity comparisons", "Pearsons_violin_comparison.eps"), p, #width=8, height=5, dpi=300, units="in")
```

Plot individual phyla colored by Class
```{r}
P6 = createPalette(6, c("#ff9933", "#00cc00", "#0080ff"))
P6 <- sortByHue(P6)
P6 <- as.vector(t(matrix(P6)))
names(P6) <- NULL

phylum_name <- 'Haptophyta'

phylum <- taxa_18S[taxa_18S$Phylum == phylum_name, ]

lm_model <- lm(X18S.reads ~ percent_TPM, data = phylum)
r_squared <- summary(lm_model)$r.squared
reads_max <- max(phylum$X18S.reads)
slope <- coef(lm_model)[2]
pearsons <- sqrt(r_squared) * sign(slope)

# no linear regression
p <- ggplot(phylum, aes(x=X18S.reads, y=percent_TPM, color=Class)) +
  geom_point(show.legend=TRUE, size=2) +
  labs(title = paste(phylum_name, "classes in paired metagenome & 18S samples"),
         x="Fraction of 18S reads", y="Fraction of eukaryotic metagenome contigs") +
  coord_cartesian(xlim = c(0, max(phylum$X18S.reads) + (0.1*max(phylum$X18S.reads))), #  
                    ylim = c(0, max(phylum$percent_TPM) + 0.1*max(phylum$percent_TPM))) + # 
  scale_x_continuous(expand=c(0, 0)) + scale_y_continuous(expand=c(0, 0)) +
  theme_classic() +
  scale_color_manual(values=P6)

ggsave(here("18S Comparison", "Class plots", paste(phylum_name, "_Classes_18S.png", sep="")), p, width=8, height=6, dpi=300, units="in")
```

Plot individual Class with points labeled
```{r}
phylum <- taxa[taxa$Phylum == 'Glaucocystophyceae', ]
class <- taxa[taxa$Class == 'Malacostraca', ]

# no linear regression
p <- ggplot(phylum, aes(x=COI.reads, y=count)) +
  geom_point(show.legend=TRUE, size=2) +
  labs(title = paste("Phylum Glaucocystophyceae in paired metagenome & 18S samples"),
         x="Fraction of COI reads", y="Fraction of eukaryotic metagenome ORFs") +
  coord_cartesian(xlim = c(0, max(class$X18S.reads) + (0.1*max(class$X18S.reads))),
                    ylim = c(0, max(class$count) + 0.1*max(class$count))) +
  scale_x_continuous(expand=c(0, 0)) + scale_y_continuous(expand=c(0, 0)) +
  theme_classic() 

#ggsave(here("18S Comparison", "Classes", "Class_Malacostraca_18S.png"), p,
 #     width=7, height=4, dpi=300, units="in")
```

